version: 2

jobs:
  buildImage:
    docker:
      - image: web3f/ci-commons:v1.0.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/build-image.sh web3f/substrate-telemetry .

  integrationTests:
    docker:
      - image: web3f/ci-commons:v1.0.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          description: run integration tests
          command: |
            /scripts/integration-tests.sh

  publishChart:
    docker:
      - image: web3f/ci-commons:v1.0.0
    steps:
      - checkout
      - run:
          command: |
            /scripts/publish-chart.sh

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - buildImage:
          filters:
            tags:
              only: /.*/
      - integrationTests:
          filters:
            tags:
              only: /.*/
      - publishChart:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - buildImage
            - integrationTests
