image:
  repo: web3f/substrate-telemetry
  tag: latest

namespace: default

environment: production

domain: testnet.w3f.tech

frontendPort: 3000
backendPort: 1024
feedPort: 8080

exporter:
  enabled: true
  port: 3000
  image:
    repo: web3f/substrate-telemetry-exporter
    tag: v0.6.0
  config:
    subscribe:
      chains:
      - kusama cc3
      validators:
      - 5D5HUyyooRU3DQKKVXQgvzuMzwdJBks5kwZHvaMgoC6PWgsa

alertrules:
  general:
    enabled: true

whiteListSourceRange: "0.0.0.0/0"
