image:
  repo: web3f/substrate-telemetry
  tag: latest

namespace: default

environment: production

domain: testnet.w3f.tech

frontendPort: 3000
backendPort: 1024
feedPort: 8080

exporter:
  enabled: true
  port: 3000
  image:
    repo: web3f/substrate-telemetry-exporter
    tag: v0.3.0

alertrules:
  enabled: true

whiteListSourceRange: "0.0.0.0/0"
