{{ if .Values.alertrules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: polkadot
  name: polkadot
spec:
  groups:
  - name: polkadot.rules
    rules:
    - alert: BlockProductionSlowDownShort
      annotations:
        message: 'Blocks were produced at 3x the previous rate for 2 minutes'
      expr: rate(polkadot_best_block[10m]) / rate(polkadot_best_block[1m]) >= 3
      for: 2m
      labels:
        severity: warning
    - alert: BlockProductionSlowDownLong
      annotations:
        message: 'Blocks were produced at 3x the previous rate for 3 minutes'
      expr: rate(polkadot_best_block[10m]) / rate(polkadot_best_block[1m]) >= 3
      for: 3m
      labels:
        severity: critical
    - alert: BlockProductionStallShort
      annotations:
        message: 'Blocks were not produced for 1 minute'
      expr: increase(polkadot_best_block[1m]) == 0
      for: 1m
      labels:
        severity: warning
    - alert: BlockProductionStallLong
      annotations:
        message: 'Blocks were not produced for 1 minute'
      expr: increase(polkadot_best_block[1m]) == 0
      for: 2m
      labels:
        severity: critical
    - alert: BlockFinalizationSlowDownShort
      annotations:
        message: 'Blocks were finalized at 3x the previous rate for 2 minutes'
      expr: rate(polkadot_best_finalized[10m]) / rate(polkadot_best_finalized[1m]) >= 3
      for: 2m
      labels:
        severity: warning
    - alert: BlockFinalizationSlowDownLong
      annotations:
        message: 'Blocks were finalized at 3x the previous rate for 3 minutes'
      expr: rate(polkadot_best_finalized[10m]) / rate(polkadot_best_finalized[1m]) >= 3
      for: 3m
      labels:
        severity: critical
    - alert: BlockFinalizationStallShort
      annotations:
        message: 'Blocks were not produced for 1 minute'
      expr: increase(polkadot_best_finalized[1m]) == 0
      for: 1m
      labels:
        severity: warning
    - alert: BlockFinalizationStallShort
      annotations:
        message: 'Blocks were not produced for 2 minutes'
      expr: increase(polkadot_best_finalized[1m]) == 0
      for: 2m
      labels:
        severity: critical
{{ end }}
