{{ if and (ne .Values.environment "ci") (.Values.alertrules.general.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: polkadot
  name: polkadot
spec:
  groups:
  - name: polkadot.rules
    rules:
    - alert: BlockProductionSlowDownShort
      annotations:
        message: 'Blocks were produced at 3x the previous rate for 2 minutes'
        runbook_url: "https://github.com/w3f/infrastructure/wiki/Block-Production-Slow-Down"
      expr: rate(polkadot_best_block[10m]) / rate(polkadot_best_block[1m]) >= 3
      for: 2m
      labels:
        severity: warning
    - alert: BlockProductionSlowDownLong
      annotations:
        message: 'Blocks were produced at 3x the previous rate for 15 minutes'
        runbook_url: "https://github.com/w3f/infrastructure/wiki/Block-Production-Slow-Down"
      expr: rate(polkadot_best_block[10m]) / rate(polkadot_best_block[1m]) >= 3
      for: 15m
      labels:
        severity: critical
    - alert: BlockProductionStallShort
      annotations:
        message: 'Blocks were not produced for 1 minute'
        runbook_url: "https://github.com/w3f/infrastructure/wiki/Block-Production-Stall"
      expr: increase(polkadot_best_block[1m]) == 0
      for: 1m
      labels:
        severity: warning
    - alert: BlockProductionStallLong
      annotations:
        message: 'Blocks were not produced for 15 minutes'
        runbook_url: "https://github.com/w3f/infrastructure/wiki/Block-Production-Stall"
      expr: increase(polkadot_best_block[1m]) == 0
      for: 15m
      labels:
        severity: critical
    - alert: BlockFinalizationSlowDownShort
      annotations:
        message: 'Blocks were finalized at 3x the previous rate for 2 minutes'
        runbook_url: "https://github.com/w3f/infrastructure/wiki/Block-Finalization-Slow-Down"
      expr: rate(polkadot_best_finalized[10m]) / rate(polkadot_best_finalized[1m]) >= 3
      for: 2m
      labels:
        severity: warning
    - alert: BlockFinalizationSlowDownLong
      annotations:
        message: 'Blocks were finalized at 3x the previous rate for 15 minutes'
        runbook_url: "https://github.com/w3f/infrastructure/wiki/Block-Finalization-Slow-Down"
      expr: rate(polkadot_best_finalized[10m]) / rate(polkadot_best_finalized[1m]) >= 3
      for: 15m
      labels:
        severity: critical
    - alert: BlockFinalizationStallShort
      annotations:
        message: 'Blocks were not finalized for 1 minute'
        runbook_url: "https://github.com/w3f/infrastructure/wiki/Block-Finalization-Stall"
      expr: increase(polkadot_best_finalized[1m]) == 0
      for: 1m
      labels:
        severity: warning
    - alert: BlockFinalizationStallLong
      annotations:
        message: 'Blocks were not finalized for 15 minutes'
        runbook_url: "https://github.com/w3f/infrastructure/wiki/Block-Finalization-Stall"
      expr: increase(polkadot_best_finalized[1m]) == 0
      for: 15m
      labels:
        severity: critical
    - alert: NewForkDetected
      annotations:
        message: 'New fork detected, please check logs'
        runbook_url: "https://github.com/w3f/infrastructure/wiki/New-Fork-Detected"
      expr: increase(polkadot_forks_total[1m]) > 0
      for: 1m
      labels:
        severity: warning
{{ end }}
