{{ if .Values.alertrules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: polkadot
  name: polkadot
spec:
  groups:
  - name: polkadot.rules
    rules:
    - alert: BlockProductionStopped
      annotations:
        message: 'Blocks were not produced in the last minute'
      expr: increase(polkadot_best_block[1m]) == 0
      for: 1m
      labels:
        severity: warning
    - alert: BlockFinalizationStopped
      annotations:
        message: 'Blocks were not finalized in the last minute'
      expr: increase(polkadot_best_finalized[1m]) == 0
      for: 1m
      labels:
        severity: warning
{{ end }}
