{{- if and (ne .Values.environment "ci") (.Values.certificate.enabled) }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Release.Name }}
spec:
  secretName: {{ include "substrate-telemetry.tlsSecretName" . }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - {{ include "substrate-telemetry.frontendDomain" . }}
  - {{ include "substrate-telemetry.backendDomain" . }}
{{- end }}
