{{- if ne .Values.environment "ci" }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ include "substrate-telemetry.tlsSecretName" . }}
  issuerRef:
    name: letsencrypt
  dnsNames:
  - {{ include "substrate-telemetry.frontendDomain" . }}
  - {{ include "substrate-telemetry.backendDomain" . }}
  acme:
    config:
    - dns01:
        provider: prod-dns
      domains:
        - {{ include "substrate-telemetry.frontendDomain" . }}
        - {{ include "substrate-telemetry.backendDomain" . }}
{{- end }}
