apiVersion: v1
kind: Service
metadata:
  name: {{ include "substrate-telemetry.frontendSvcName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "substrate-telemetry.frontendSvcName" . }}
spec:
  ports:
  - name: frontend
    port: {{ .Values.frontendPort }}
  selector:
    app: {{ include "substrate-telemetry.frontendAppName" . }}
