apiVersion: v1
kind: Service
metadata:
  name: {{ include "substrate-telemetry.backendSvcName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "substrate-telemetry.backendSvcName" . }}
spec:
  ports:
  - name: backend
    port: {{ .Values.backendPort }}
  - name: feed
    port: {{ .Values.feedPort }}
  selector:
    app: {{ include "substrate-telemetry.backendAppName" . }}
